name: Deploy to server

on:
  push:
    branches: [development]

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Work dir
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
  second_jobs:
    if: ${{ github.ref == 'refs/heads/development' }}
    needs: first_jobs #Permite hace secuenciales los jobs

    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ github.ref }}"
