name: Deploy to server

on:
  push:
    branches: [development]

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    env:
      NAME: CodigoFacilito

    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo ${{ steps.step_1.outputs.my_variable }}

  second_jobs:
    if: ${{ github.ref == 'refs/heads/development' }}
    needs: first_jobs #Permite hace secuenciales los jobs
    runs-on: ubuntu-latest

    env:
      salida: ${{needs.first_jobs.outputs.salida}}

    steps:
      - name: Hola Mundo
        run: echo "${{salida}}"
