name: Deploy to server

on:
  push:
    branches: [development]

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_jobs:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_jobs #Permite hace secuenciales los jobs

    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo"
